### ISSUE TITLE
scan giving an address (format?) that isn't recognised

### ISSUE THREAD

**Issue by GodotIsWaitingToo** [tahnok/colmi_r02_client#1]
When I run 

`colmi_r02_util scan`

in pipx, I get the following address, that then isn't recognised when input into the client:

`88C7C179-BD9A-852A-12C9-28FDFFF535CF`

It is possible that this is because I'm using an R06 ring rather than R02, but I'm sceptical

**Comment by tahnok** [comment]
Are you on a Mac?

**Comment by GodotIsWaitingToo** [comment]
Yes, I am

**Comment by tahnok** [comment]
Hmm, seems like that's how macos/bleak represent addresses. I don't have a
mac to test on, can you tell me exactly what the error is?

The docs seem to indicate you can just pass the UUID to the connect method,
but maybe it's ephemeral and changes between runs of the program

**Comment by tahnok** [comment]
I've added a `--name` option you can use instead of `--address`, do you want to see if that works?

**Comment by tahnok** [comment]
In particular it lets you use the name of the device instead of the address. It will be a bit slower since it scans for devices and then connects

**Comment by GodotIsWaitingToo** [comment]
Thanks! I'm still not succeeding. I've attached a screenshot of what the error looks like:
<img width="1042" alt="Screenshot 2024-09-23 at 22 37 33" src="https://github.com/user-attachments/assets/4de9ee68-8bea-4822-a0e3-3d4573d2890e">

**Comment by tahnok** [comment]
Try it again, but delete the leading # from all the commands

**Comment by GodotIsWaitingToo** [comment]
Oh dear... thank you! So the address with the MacOS-style address is working, --name isn't, but it's now connecting and giving the heart rate reading successfully. All the other commands are working too.

**Comment by tahnok** [comment]
Glad to hear it! Feels good to know someone else is using my code

How did you find the repo?

**Comment by GodotIsWaitingToo** [comment]
Haha - it's excellent work, keep going!

I think I found it via this thread:

https://github.com/atc1441/ATC_RF03_Ring/issues/13
