### ISSUE TITLE
Full data sync to sqlite

### ISSUE THREAD

**Issue by tahnok** [tahnok/colmi_r02_client#14]
Implement a feature that will sync all data from the ring (steps, heart rate, spo2) into a sqlite database.

The goal is to have a single `colmi_r02_client sync database_file.sqlite` command that will pull all available data off the ring. It should be smart enough to know when the last sync was so that it can fetch just the new data

TODO:

- [ ] pick library for sqlite
- [ ] decide if I want to use an ORM
- [ ] design the table schema

**Comment by jrobsontull** [comment]
ORM would be a nice touch!
