### ISSUE TITLE
Scanning to find the R10

### ISSUE THREAD

**Issue by SxMShaDoW** [tahnok/colmi_r02_client#30]
Hey!

Love the work and excited about the progress. I recently got the R10 (which the quick guide talks about QRing) and tried using the scan functionality and it doesn't seem to find it.

I verified that gadgetbride can find the ring - so I am not sure why this client can't.

Let me know what I should try or test. 

Tested with: Macbook Air M2:

```
me@MacBook-Air % colmi_r02_util scan
Found device(s)
                Name  | Address
--------------------------------------------
````

**Comment by tahnok** [comment]
Known issue, you can pass the `--all` flag to the scan command and you should see a `COLMI R10`

**Comment by tahnok** [comment]
Fixed now, I can find my R10
