### ISSUE TITLE
Use last sync date for specific ring

### ISSUE THREAD

**Issue by TonyGiorgio** [tahnok/colmi_r02_client#33]
Minor issue, I'm just doing tests with multiple rings but right now the last sync time isn't device specific so it misses data from one of the rings if the other ring was synced last. 

```
colmi_r02_client --address={device_1} sync
ring_data.sqlite
Syncing from 2024-12-01 05:35:16.240327+00:00 to 2024-12-08 05:35:16.240333+00:00
Ignore unexpect packet
Done
colmi_r02_client --address={device_2} sync
ring_data.sqlite
Syncing from 2024-12-08 05:35:21.599767+00:00 to 2024-12-08 05:35:28.802938+00:00
Ignore unexpect packet
Done
```

Fix looks like it might be by passing the ring address to this function: 

https://github.com/tahnok/colmi_r02_client/blob/main/colmi_r02_client/db.py#L165-L166

```py
def get_last_sync(session: Session) -> datetime | None:
    return session.scalars(func.max(Sync.timestamp)).one_or_none()
```

Temp solution is to use two different sqlite files for each ring.

**Comment by tahnok** [comment]
Good catch, should be fixed now
