### ISSUE TITLE
Web interface

### ISSUE THREAD

**Issue by agamm** [tahnok/colmi_r02_client#7]
Any plans on creating something that I can use from my computer/mobile phone?

If not, what should I start to work on it?

**Comment by sebws** [comment]
WebBluetooth exists and could probably be used for something like this. However, it's [quite limited in availability](https://caniuse.com/web-bluetooth) and it doesn't look like it's growing any larger.

**Comment by agamm** [comment]
You can use a [PWA](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps) for mobile?

**Comment by sebws** [comment]
You're still restricted to WebBluetooth limitations

**Comment by tahnok** [comment]
Yeah, a separate PWA that uses WebBluetooth would be a cool way to write an open and cross platform client, but no way I can see python or this codebase working for that

**Comment by tahnok** [comment]
Created #15 and will close this in favour of that one
